### ISSUE TITLE
Contact Form for Reach Out Section

### ISSUE THREAD

**Issue by kakudiego** [kakudiego/run-buddy#2]
# Contact Form for Reach Out Section

## Content Requirements
* Heading: "Contact Us"
* Name: Input Text field
* Message: Large message area

**Comment by TheV4Tican** [comment]
I can give this a shot if you would like? I'm new to the github world and could use some contribution experience.

**Comment by kakudiego** [comment]
> I can give this a shot if you would like? I'm new to the github world and could use some contribution experience.

hi, I'm just training here, but thx
